
# Configuración de Yarn para EscalaFin MVP
# Forzar uso de node_modules tradicional (no Plug'n'Play)

nodeLinker: node-modules

# Deshabilitar telemetría
enableTelemetry: false

# Configuración de red
httpTimeout: 60000
networkTimeout: 60000

# Configuración de caché
enableGlobalCache: false
